//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensePortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ExpenseRecord
    {
        public int ExpenseRecordId { get; set; }

        [Required]
        public string Title { get; set; }
        public string Description { get; set; }

        [DisplayName("Receipt")]
        public string ReceiptImagePath { get; set; }

        [DisplayName("Requester Name")]
        public string RequesterUserId { get; set; }

        [DisplayName("Approver Name")]
        public string ApproverId { get; set; }

        [DisplayName("Status")]
        public Nullable<byte> ApprovalStatusId { get; set; }

        [DisplayName("Comments")]
        public string ApproverComment { get; set; }

        [DisplayName("Submitted Date")]
        public Nullable<System.DateTime> SubmittedDate { get; set; }

        [DisplayName("Reviewed Date")]
        public Nullable<System.DateTime> ApprovedOrRejectedDate { get; set; }
        public HttpPostedFileBase ReceiptImageFile { get; set; }

        public virtual ExpenseRecord ExpenseRecord1 { get; set; }
        public virtual ExpenseRecord ExpenseRecord2 { get; set; }
    }
}
